FROM rust:1.90.0-bookworm AS builder
WORKDIR /app
COPY . .
RUN cargo build -p worker --release

FROM debian:bookworm-slim AS runtime
WORKDIR /app
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/worker ./worker
ENTRYPOINT ["./worker"]
