mod color_switcher;
mod discord_link;
mod footer;
mod fuzzy_search;
mod gearmap;
mod github_link;
mod header_nav;
mod language_switcher;
mod theme_switcher;
mod user_profile;

pub use color_switcher::ColorSwitcher;
pub use discord_link::DiscordLink;
pub use footer::Footer;
pub use fuzzy_search::FuzzySearch;
pub use github_link::GithubLink;
pub use header_nav::HeaderNav;
pub use language_switcher::LanguageSwitcher;
pub use theme_switcher::ThemeSwitcher;
pub use user_profile::UserProfile;
