name: bestofrs worker
on:
  schedule:
    - cron: "0 0 * * *" # UTC 00:00
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: [self-hosted, bestofrs, worker]
    steps:
      - name: Run worker
        run: |
          cd /home/zyzj/bestofrs
          docker compose -f compose-worker.yaml run --rm worker
