name: bestofrs worker
on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes (test)
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: [self-hosted, bestofrs, worker]
    steps:
      - name: Run worker
        run: |
          cd /home/zyzj/bestofrs
          docker compose -f compose-worker.yaml run --rm worker
